version: "2"

services:
    strichliste:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 8080:8080
        networks:
            - db_net
        volumes:
             - ./config/services.yaml:/source/config/services.yaml
             - ./config/strichliste.yaml:/source/config/strichliste.yaml
             - ./config/doctrine.yaml:/source/config/packages/doctrine.yaml
             - ./config/default.conf:/etc/nginx/conf.d/default.conf
        environment:
            - APP_ENV=prod
            - DB_HOST=strichliste_db
            - DATABASE_URL=mysql://strichliste:strichliste@strichliste_db/strichliste


        # Traefik configuration
        # labels:
        #     - "traefik.docker.network={your traefik network}"
        #     - "traefik.frontend.rule=Host:{URL}"
        #     - "traefik.enable=true"
        #     - "traefik.port=8080"
    strichliste_db:
        image: mariadb:latest
        restart: always
        networks:
            - db_net
        environment:
            - MARIADB_ROOT_PASSWORD=strichliste
            - MARIADB_DATABASE=strichliste
            - MARIADB_USER=strichliste
            - MARIADB_PASSWORD=strichliste
        volumes:
            - ./data/mysql:/var/lib/mysql


networks:
    db_net:
