version: "2"
networks:
    web:
        external: true
services:
    strichliste:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        # if you use traefik you can remove the ports section
        ports:
            - 8080:8080
        networks:
            # - traefik_network  # your traefik network
            - default
        volumes:
             - ./config/services.yaml:/source/config/services.yaml
             - ./data/app.db:/source/var/app.db
        # Traefik configuration
        # labels:
        #     - "traefik.docker.network={your traefik network}"
        #     - "traefik.frontend.rule=Host:{URL}"
        #     - "traefik.enable=true"
        #     - "traefik.port=8080"
