version: "2"
networks:
    web:
        external: true    
services:
    strichliste:
        build:
            context: .
            dockerfile: ./data/Dockerfile
        networks:
            - web
            - default
        volumes:
             - ./data/services.yaml:/source/config/services.yaml
             - ./data/app.db:/source/var/app.db
        labels:
            - "traefik.docker.network=web"
            - "traefik.frontend.rule=Host:{URL}"
            - "traefik.enalbe=true"
            - "traefik.port=8080"
